repos:
- repo: local
  hooks:
  - id: shellcheck
    name: Lint Bash
    entry: bin/lint/shell
    args: [check]
    language: script
    files: ^.*\.sh|^bin/
    exclude: ^.*\.yaml
  - id: python
    name: Lint Python
    entry: bin/lint/py
    language: python
  - id: md
    name: Lint Markdown
    entry: bin/lint/md
    args: [--fix]
    language: script
    types: [ text , markdown ]
